/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sim;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.*;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class loging extends javax.swing.JFrame {

  File file = new File("userID.txt");  
  
  File file2 = new File("userN.txt");  
  File file3 = new File("totalStudent.txt");  
  File file4 = new File("totalCourse.txt");  
//    public static int uid;
 String valueID="";    
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

 
    public loging() throws IOException {
        initComponents();
            lbl_u.setVisible(false);
            lbl_p.setVisible(false);
       Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        
//        writedata();
//        readdata();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCancle = new javax.swing.JButton();
        btnloging = new javax.swing.JButton();
        ckedBoxpassVesibl = new javax.swing.JCheckBox();
        lbl_p = new javax.swing.JLabel();
        lbl_u = new javax.swing.JLabel();
        txtP = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtU = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnCancle.setBackground(new java.awt.Color(255, 153, 0));
        btnCancle.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        btnCancle.setText("cancle");
        btnCancle.setToolTipText("click here if you aint to loging");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        btnloging.setBackground(new java.awt.Color(52, 189, 255));
        btnloging.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        btnloging.setText("loging");
        btnloging.setToolTipText("click to loging to your system");
        btnloging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogingActionPerformed(evt);
            }
        });

        ckedBoxpassVesibl.setBackground(new java.awt.Color(102, 102, 102));
        ckedBoxpassVesibl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckedBoxpassVesibl.setForeground(new java.awt.Color(255, 255, 255));
        ckedBoxpassVesibl.setText("show password");
        ckedBoxpassVesibl.setToolTipText("");
        ckedBoxpassVesibl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckedBoxpassVesiblActionPerformed(evt);
            }
        });

        lbl_p.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_p.setForeground(new java.awt.Color(255, 0, 0));
        lbl_p.setText("*");

        lbl_u.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_u.setForeground(new java.awt.Color(255, 0, 0));
        lbl_u.setText("*");

        txtP.setBackground(new java.awt.Color(208, 216, 154));
        txtP.setFont(new java.awt.Font("Gisha", 1, 17)); // NOI18N
        txtP.setToolTipText("enter your  password");
        txtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pasword ");

        txtU.setBackground(new java.awt.Color(208, 216, 154));
        txtU.setFont(new java.awt.Font("Gisha", 1, 17)); // NOI18N
        txtU.setToolTipText("enter your user name");
        txtU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnloging, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtU, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_u, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_p, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckedBoxpassVesibl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_u, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_p, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckedBoxpassVesibl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloging, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        jLabel2.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("L o g i n g    S y s t e m");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        int confirmEXITt= JOptionPane.showConfirmDialog(null, "Do you really want to exit ?","EXIT !",JOptionPane.YES_NO_OPTION);

        if (confirmEXITt==0) {

            System.exit(0);

        }
        else{

        }

    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnlogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogingActionPerformed
        String N;
        char[] P;
        N = txtU.getText();
        P = txtP.getPassword();//return char array
        String pass = String.valueOf(P);//convert char array to string
        if (N.isEmpty()) {
            lbl_u.setVisible(true);
            JOptionPane.showMessageDialog(rootPane, "Enter user name ! ");

            lbl_u.requestFocus();
        } else if (String.valueOf(txtP.getPassword()).isEmpty()) {
            lbl_p.setVisible(true);
            JOptionPane.showMessageDialog(rootPane, "Enter user Password ! ");
            lbl_p.requestFocus();
        } else {
                        lbl_u.setVisible(false);
                        lbl_p.setVisible(false);

            Connection conn = connectionDB.connection_DB();
          

            try {
                pst = conn.prepareStatement("SELECT * FROM user where user_name= ? and password=?");
                pst.setString(1, N);
                pst.setString(2, pass);

                ResultSet rs = pst.executeQuery();
                int count = 0;
                while (rs.next()) {
                   
                    count = rs.getRow();
                                 int id = rs.getInt(1);
                                 
                                  Emp.empId = id;
                                  Emp.empUSER =N;
                                  Emp.T_Student =Integer.toString(MyFunction.countData("students"));
                                  Emp.T_Course =Integer.toString(MyFunction.countData("course"));
                                  
                                  
                                  
                               System.out.println("loged id  :"+ Emp.empId); 
                               System.out.println(N); 
                               
                    try {
                        writedata();
                    } catch (IOException ex) {
                        Logger.getLogger(loging.class.getName()).log(Level.SEVERE, null, ex);
                    }
                                  
                }

                if (count > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Login Successful!");

                            HomeWindow hw = new HomeWindow();
                            
                            hw.setVisible(true);
                    hw.lbluser.setText("You are loged as  " +N);
                   
                    hw.pack();
                    hw.setLocationRelativeTo(null);
                    //                    mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    hw.cc.setText("Total Students : "+Integer.toString(MyFunction.countData("students")));
                    hw.cs.setText("Available Courses : "+Integer.toString(MyFunction.countData("course")));
                    txtU.setText("");
                    txtP.setText("");
                    lbl_u.setVisible(false);
                    lbl_p.setVisible(false);
                    
                   try {
                  Date currentDate = GregorianCalendar.getInstance().getTime();
                  DateFormat df = DateFormat.getDateInstance();
                  String dateString = df.format(currentDate);

                  Date d = new Date();
                  SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                  String timeString = sdf.format(d);

                  String value0 = timeString;
                  String values = dateString;
                  String signed = "Logged in";
                   conn = connectionDB.connection_DB();
                    
//                    Emp e = new Emp();
//                    int userid=Emp.empId;






                String valueID = String.valueOf(Emp.empId) ;
                String reg = "INSERT into userlog (emp_id,date,status) VALUES (?,?,?)";
                pst=conn.prepareStatement(reg);
                pst.setString(1, valueID);
                pst.setString(2, value0+" / "+values);
                pst.setString(3, signed);
                pst.execute();
                   
                   } catch (Exception e) {
                       e.printStackTrace();
                   } 
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Login Fail!");
                    lbl_u.setVisible(true);
                    lbl_p.setVisible(true);

                }
                rs.close();
                pst.close();
                conn.close();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnlogingActionPerformed

    private void ckedBoxpassVesiblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckedBoxpassVesiblActionPerformed

        if (ckedBoxpassVesibl.isSelected()) {
            txtP.setEchoChar((char)0);
        } else {
            txtP.setEchoChar('*');
        }

    }//GEN-LAST:event_ckedBoxpassVesiblActionPerformed

    private void txtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPActionPerformed

    private void txtUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loging().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(loging.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
     public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
//        txt_date.setText((month+1)+"/"+day+"/"+year);
    }
     public void writedata() throws IOException {
        BufferedWriter buf = null;
        BufferedWriter buf2 = null;
        BufferedWriter buf3 = null;
        BufferedWriter buf4 = null;
        
        try {
            buf = new BufferedWriter(new FileWriter(file));            
            buf2 = new BufferedWriter(new FileWriter(file2));            
            buf3 = new BufferedWriter(new FileWriter(file3));            
            buf4 = new BufferedWriter(new FileWriter(file4));            
            buf.write( String.valueOf(Emp.empId));
            buf2.write( String.valueOf(Emp.empUSER));
            buf3.write( String.valueOf(Emp.T_Student));
            buf4.write( String.valueOf(Emp.T_Course));
            buf.newLine();
            buf2.newLine();
            buf3.newLine();
            buf4.newLine();
            
          
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (buf != null || buf2 != null|| buf3 != null|| buf4 != null) {
                buf.close();
                buf2.close();
                buf3.close();
                buf4.close();
            }
        }
    }  
  
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnloging;
    private javax.swing.JCheckBox ckedBoxpassVesibl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_p;
    private javax.swing.JLabel lbl_u;
    private javax.swing.JPasswordField txtP;
    private javax.swing.JTextField txtU;
    // End of variables declaration//GEN-END:variables
}
