/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sim;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import static javax.swing.UIManager.getInt;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SAM
 */
public class manageStudent3 extends javax.swing.JFrame {

    private ImageIcon format = null;
    //strin filename
    String filename = null;
    String gender;
    public byte[] person_image;

    student s = new student();

    public manageStudent3() {
        initComponents();
        this.person_image = null;
//        loadScheduleList(JComboBox combo)
        loadComboLABEL(COURSELABEL);
        s.loadComboBatch(BATCHNAME);

        show_user();
//       int statusWIND=hw.getExtendedState();
//	    jDateChooser1.setCurrent(null);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);
        
        jTable_Display_User.setBackground(new Color(0,0,0,0));
      ((DefaultTableCellRenderer)jTable_Display_User.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0))  ;
        
        jTable_Display_User.setGridColor(Color.WHITE);
        jTable_Display_User.setForeground(Color.WHITE);
        jScrollPane1.setOpaque(false);
        jTable_Display_User.setOpaque(false);
       ((DefaultTableCellRenderer)jTable_Display_User.getDefaultRenderer(Object.class)).setOpaque(false)  ; 
        jScrollPane1.getViewport().setOpaque(false);
    }

    public ArrayList<User> userList() {

        ArrayList<User> userList = new ArrayList<>();

        try {
            Connection con = connectionDB.connection_DB();
            String query1 = "SELECT * from students ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            User user;
            while (rs.next()) {
                user = new User(rs.getInt("st_id"), rs.getString("first_name"), rs.getString("last_name"), rs.getString("dob"), rs.getString("gender"), rs.getString("phone"), rs.getString("address"), rs.getString("email"), rs.getString("post_code"), rs.getBytes("st_image")
                , rs.getString("label"), rs.getString("batch_name"), rs.getDouble("fees"), rs.getString("schedule"), rs.getString("reg_date")
                );
                userList.add(user);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return userList;
    }

    public void show_user() {
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
        Object[] row = new Object[15];
        for (int i = 0; i < list.size(); i++) {
            Object object = row[i];
            row[0] = list.get(i).getst_id();
            row[1] = list.get(i).getfirst_name();
            row[2] = list.get(i).getlast_name();
            row[3] = list.get(i).getdob();
            row[4] = list.get(i).getgender();
            row[5] = list.get(i).getphone();
            row[6] = list.get(i).getaddress();
            row[7] = list.get(i).getemail();
            row[8] = list.get(i).getpost_code();
            row[9] = list.get(i).getst_image();
            row[10] = list.get(i).getlabel();
            row[11] = list.get(i).getbatch_name();
            row[12] = list.get(i).getfees();
            row[13] = list.get(i).getschedule();
            row[14] = list.get(i).getreg_date();
           
            
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENDER = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_backHome = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MALE = new javax.swing.JRadioButton();
        FEMALE = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        txtPHONE = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtADDRESS = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPOSTCODE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmd_save1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        BTN_addStU1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchID = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FEES = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel35 = new javax.swing.JLabel();
        BATCHNAME = new javax.swing.JComboBox<>();
        COURSELABEL = new javax.swing.JComboBox<>();
        SCHEDULE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Manage Student");
        setBackground(new java.awt.Color(102, 102, 102));
        setSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("M a n a g e   R e g i s t r a t i o n");
        jLabel5.setOpaque(true);

        btn_backHome.setBackground(new java.awt.Color(255, 255, 255));
        btn_backHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/navigateIMG/icons8_Rewind_64px.png"))); // NOI18N
        btn_backHome.setToolTipText("back to home page ");
        btn_backHome.setOpaque(true);
        btn_backHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_backHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_backHomeMouseReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ID");

        txtFN.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtFN.setToolTipText("enter first name");
        txtFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("First Name :");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Last Name :");

        txtLN.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtLN.setToolTipText("enter last name");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("DOB");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Gender :");

        MALE.setBackground(new java.awt.Color(244, 242, 232));
        GENDER.add(MALE);
        MALE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MALE.setForeground(new java.awt.Color(255, 255, 255));
        MALE.setSelected(true);
        MALE.setText("Male");
        MALE.setOpaque(false);
        MALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MALEActionPerformed(evt);
            }
        });

        FEMALE.setBackground(new java.awt.Color(244, 242, 232));
        GENDER.add(FEMALE);
        FEMALE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FEMALE.setForeground(new java.awt.Color(255, 255, 255));
        FEMALE.setText("Female");
        FEMALE.setOpaque(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Phone :");

        txtPHONE.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtPHONE.setToolTipText("enter phone number(number only)");
        txtPHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPHONEActionPerformed(evt);
            }
        });
        txtPHONE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPHONEKeyTyped(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Address");

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        txtADDRESS.setColumns(20);
        txtADDRESS.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtADDRESS.setRows(5);
        txtADDRESS.setToolTipText("enter address");
        jScrollPane2.setViewportView(txtADDRESS);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Email");

        txtEMAIL.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtEMAIL.setToolTipText("enter email address");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Post Code");

        txtPOSTCODE.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtPOSTCODE.setToolTipText("enter postal code");
        txtPOSTCODE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPOSTCODEKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT PHOTO");

        cmd_save1.setBackground(new java.awt.Color(51, 51, 51));
        cmd_save1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_FINAL/icons8_Add_Camera_12px.png"))); // NOI18N
        cmd_save1.setToolTipText("choose your image");
        cmd_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_save1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(139, 238, 178));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/20px/icons8_Available_Updates_20px.png"))); // NOI18N
        jButton1.setText("Reset");
        jButton1.setToolTipText("click here to reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_img.setBackground(new java.awt.Color(153, 153, 153));

        jDesktopPane1.setLayer(lbl_img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable_Display_User.setBackground(new java.awt.Color(204, 255, 204));
        jTable_Display_User.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jTable_Display_User.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable_Display_User.setForeground(new java.awt.Color(255, 255, 255));
        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Dath of Birth", "Gender", "Phone", "Address", "Email", "Post Code", "Photo", "Course Label", "Batch Name", "Fees", "Schedule", "Reg_Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Display_User.setGridColor(new java.awt.Color(255, 255, 51));
        jTable_Display_User.setRowHeight(40);
        jTable_Display_User.setSelectionBackground(new java.awt.Color(102, 255, 204));
        jTable_Display_User.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_User);

        btnUPDATE.setText("Update");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnDELETE.setText("Delete");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtID.setToolTipText("Student id not editable !");

        BTN_addStU1.setBackground(new java.awt.Color(51, 176, 50));
        BTN_addStU1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BTN_addStU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/20px/icons8_Add_20px_1.png"))); // NOI18N
        BTN_addStU1.setText("Add");
        BTN_addStU1.setToolTipText("click here to add new student");
        BTN_addStU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_addStU1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(126, 175, 244));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Student", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID  :");

        searchID.setBackground(new java.awt.Color(255, 255, 204));
        searchID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchID.setForeground(new java.awt.Color(0, 0, 255));
        searchID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Label");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Fee");

        FEES.setEditable(false);
        FEES.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        FEES.setToolTipText("");
        FEES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEESActionPerformed(evt);
            }
        });
        FEES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FEESKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Schedule");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registration Date");

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Batch Name");

        BATCHNAME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BATCHNAME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BATCHNAME.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                BATCHNAMEPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        BATCHNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BATCHNAMEActionPerformed(evt);
            }
        });

        COURSELABEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        COURSELABEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        COURSELABEL.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                COURSELABELPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        SCHEDULE.setEditable(false);
        SCHEDULE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd_save1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(MALE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(FEMALE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLN)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPHONE)))
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPOSTCODE)
                                .addComponent(txtEMAIL)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(COURSELABEL, 0, 214, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FEES)
                                .addComponent(SCHEDULE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BATCHNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTN_addStU1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(4, 4, 4))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MALE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FEMALE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addComponent(txtPHONE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPOSTCODE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cmd_save1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(COURSELABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(BATCHNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FEES, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCHEDULE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BTN_addStU1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_backHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_backHome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1162, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backHomeMouseClicked
        HomeWindow hw = new HomeWindow();
        this.dispose();

        hw.setVisible(true);


    }//GEN-LAST:event_btn_backHomeMouseClicked

    private void btn_backHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backHomeMousePressed
        btn_backHome.setBackground(new Color(139, 238, 178));
    }//GEN-LAST:event_btn_backHomeMousePressed

    private void btn_backHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backHomeMouseReleased
        btn_backHome.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_backHomeMouseReleased

    private void txtPHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPHONEActionPerformed

    }//GEN-LAST:event_txtPHONEActionPerformed

    private void txtPHONEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPHONEKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            //st_id, first_name, last_name, dob, gender, phone, address, email, post_code, st_image

        }
    }//GEN-LAST:event_txtPHONEKeyTyped

    public boolean verify() {
        int atp = txtEMAIL.getText().indexOf("@");
        int dotp = txtEMAIL.getText().lastIndexOf(".");
        int len = txtEMAIL.getText().length();

        if (txtFN.getText().isEmpty() || txtLN.getText().isEmpty() || txtPHONE.getText().isEmpty() || txtADDRESS.getText().isEmpty() || txtEMAIL.getText().isEmpty() || txtPOSTCODE.getText().isEmpty()
                || lbl_img.getIcon() == null || jDateChooser1.getCalendar() == null||jDateChooser2.getCalendar() == null||COURSELABEL.getSelectedIndex()==0||BATCHNAME.getSelectedIndex()==0|| SCHEDULE.getText().isEmpty()|| FEES.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "One or more fields are empty / not selected");
            return false;
        } else if (jDateChooser1.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(rootPane, "No student from future are allow");
            return false;
        } else if (atp < 1 || dotp < atp + 2 || dotp + 2 > len) {
            JOptionPane.showMessageDialog(rootPane, "Enteralid Email address ");
            return false;
        } else {
            return true;
        }

    }


    private void cmd_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_save1ActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            filename = f.getAbsolutePath();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
            lbl_img.setIcon(imageIcon);

            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {

                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
          e.getMessage();

        }

    }//GEN-LAST:event_cmd_save1ActionPerformed

    private void txtPOSTCODEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPOSTCODEKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPOSTCODEKeyTyped

    private void MALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MALEActionPerformed

    public void clearfield() {

        FEES.setText("");
        txtID.setText("");
        txtFN.setText("");
        txtLN.setText("");
        txtPHONE.setText("");
        txtPOSTCODE.setText("");
        txtEMAIL.setText("");
        txtADDRESS.setText("");
        GENDER.clearSelection();
        jDateChooser1.setCalendar(null);
        jDateChooser2.setCalendar(null);
        lbl_img.setIcon(null);
        SCHEDULE.setText("");
        COURSELABEL.setSelectedIndex(0);
        BATCHNAME.setSelectedIndex(0);

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearfield();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNActionPerformed

    private void BTN_addStU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_addStU1ActionPerformed
        double fees = 0.00;

        String first_name = txtFN.getText();

        String last_name = txtLN.getText();

        String gender = "Male";
        if (MALE.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }
        String phone = txtPHONE.getText();
        String address = txtADDRESS.getText();
        String email = txtEMAIL.getText();
        String post_code = txtPOSTCODE.getText();
        byte[] st_image = person_image;
        
        String label = COURSELABEL.getSelectedItem().toString();
        try {
            fees = Double.parseDouble(FEES.getText());
        } catch (NumberFormatException e) {
            e.getMessage();
        }
        String schedule= SCHEDULE.getText();
      String batch_name =BATCHNAME.getSelectedItem().toString();

        if (verify()) {
            
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
            SimpleDateFormat sdf2 = new SimpleDateFormat("yyy-MM-dd");
            String dob = sdf.format(jDateChooser1.getDate());
            String reg_date = sdf2.format(jDateChooser2.getDate());
            student std = new student();
            std.insertUpdateDeleteStudent('i', null, first_name, last_name, dob, gender, phone, address, email, post_code, st_image,label, batch_name, fees, schedule, reg_date);
            HomeWindow hw = new HomeWindow();
            hw.cc.setText("Total Students : "+Integer.toString(MyFunction.countData("students")));
        }
        DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
        model.setRowCount(0);
        show_user();
        clearfield();

    }//GEN-LAST:event_BTN_addStU1ActionPerformed

    private void jTable_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_UserMouseClicked

        int i = jTable_Display_User.getSelectedRow();
        TableModel model = jTable_Display_User.getModel();
        txtID.setText(model.getValueAt(i, 0).toString());
        txtFN.setText(model.getValueAt(i, 1).toString());
        txtLN.setText(model.getValueAt(i, 2).toString());
        try {
            Date date = new SimpleDateFormat("yyy-MM-dd").parse((String) model.getValueAt(i, 3));
            jDateChooser1.setDate(date);
            String gen = model.getValueAt(i, 4).toString();
            if (gen.equals("Male")) {
                MALE.setSelected(true);
            }
            if (gen.equals("Female")) {
                FEMALE.setSelected(true);
            }

            txtPHONE.setText(model.getValueAt(i, 5).toString());
            txtADDRESS.setText(model.getValueAt(i, 6).toString());
            txtEMAIL.setText(model.getValueAt(i, 7).toString());
            txtPOSTCODE.setText(model.getValueAt(i, 8).toString());
            byte[] img = (userList().get(i).getst_image());
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
            lbl_img.setIcon(imageIcon);
            person_image = img;
            try {
                COURSELABEL.setSelectedItem(jTable_Display_User.getValueAt(i, 10).toString());
//                autoload();
                  Date date2 = new SimpleDateFormat("yyy-MM-dd").parse((String) model.getValueAt(i, 13));
            
            jDateChooser2.setDate(date2);
            
//            BATCHNAME.setSelectedItem(jTable_Display_User.getValueAt(i, 15).toString());
            } catch (Exception e) {
            }
             
             FEES.setText(jTable_Display_User.getValueAt(i, 12).toString());
             SCHEDULE.setText(jTable_Display_User.getValueAt(i, 13).toString());
             Date date2 = new SimpleDateFormat("yyy-MM-dd").parse((String) model.getValueAt(i, 14));
            
            jDateChooser2.setDate(date2);
//            
            BATCHNAME.setSelectedItem(jTable_Display_User.getValueAt(i, 11).toString());
             
             
        } catch (ParseException ex) {
//            JOptionPane.showMessageDialog(rootPane, ex);
ex.printStackTrace();
        }


    }//GEN-LAST:event_jTable_Display_UserMouseClicked

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
       
         double fees = 0.00;
        int confrm = JOptionPane.showConfirmDialog(null, "Are you sure to Update ?", "Update", JOptionPane.YES_NO_OPTION);
        if (confrm == 0) {
            try {

                int idx = Integer.valueOf(txtID.getText());
                String fname = txtFN.getText();
                String lname = txtLN.getText();
                String ph = txtPHONE.getText();
                String addrs = txtADDRESS.getText();
                String mailrr = txtEMAIL.getText();
                String pstcd = txtPOSTCODE.getText();
                String sext = "Male";
                if (FEMALE.isSelected()) {
                    sext = "Female";

                }
                byte[] st_image = person_image;
                String label = COURSELABEL.getSelectedItem().toString();
        try {
            fees = Double.parseDouble(FEES.getText());
        } catch (NumberFormatException e) {
            e.getMessage();
        }
        String schedule= SCHEDULE.getText();
      String batch_name =BATCHNAME.getSelectedItem().toString();

                if (verify()) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
                    String dob = sdf.format(jDateChooser1.getDate());
                    student std = new student();
                    SimpleDateFormat sdf2 = new SimpleDateFormat("yyy-MM-dd");
                    String reg_date = sdf2.format(jDateChooser2.getDate());
                    
                    std.insertUpdateDeleteStudent('u', idx, fname, lname, dob, sext, ph, addrs, mailrr, pstcd, st_image,label, batch_name, fees, schedule, reg_date);
                    DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
                      HomeWindow hw = new HomeWindow();
                    hw.cc.setText("Total Students : "+Integer.toString(MyFunction.countData("students")));
                    model.setRowCount(0);
                    show_user();
                    clearfield();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Select one to Update data");
                System.out.println(e.getMessage());
            }
        }



    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed

        
        
        
        int confrm = JOptionPane.showConfirmDialog(null, "Are you sure to delete ? Student Score also be Deleted !!", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confrm == 0) {
            try {
                Connection con = connectionDB.connection_DB();
                int row = jTable_Display_User.getSelectedRow();
                String value = (jTable_Display_User.getModel().getValueAt(row, 0).toString());
                String querry4 = "DELETE FROM students WHERE st_id=" + value;
                PreparedStatement pst = con.prepareStatement(querry4);
                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
                HomeWindow hw = new HomeWindow();
                hw.cc.setText("Total Students : " + Integer.toString(MyFunction.countData("students")));
                model.setRowCount(0);

                JOptionPane.showMessageDialog(null, "Data Deleted Successfully");
                show_user();

//                   hw.cs.setText(Integer.toString(MyFunction.countData("student")));
                clearfield();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Select one to Delete data");
                System.out.println(e.getMessage());
            }

        }


    }//GEN-LAST:event_btnDELETEActionPerformed
public void SearchByID() {
        String stID = searchID.getText();
        Connection conn = connectionDB.connection_DB();
        PreparedStatement pst = null;
        ResultSet rs=null;
        try {

            conn = connectionDB.connection_DB();
            String sql = "SELECT * FROM students  where st_id='" + stID + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable_Display_User.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {

            try {
                rs.close();
                pst.close();

            } catch (Exception e) {

            }
        }
    }
//    private void DETAILS1() {
//        try {
//
//            conn = connectionDB.connection_DB();
//            String sql = "SELECT st_id, first_name, last_name,st_image,label,\n"
//                    + " batch_name, schedule, reg_date, scoreId, ex_id,\n"
//                    + " ex_date, full_marks, score_written,\n"
//                    + "  score_evedence, Score_Total, parcentage,\n"
//                    + "  remarks FROM report";
//
//            pst = conn.prepareStatement(sql);
//            rs = pst.executeQuery();
//            table_details.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        } finally {
//
//            try {
//                rs.close();
//                pst.close();
//
//            } catch (Exception e) {
//
//            }
//        }
//    }



    private void searchIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchIDKeyReleased
SearchByID();
        if (searchID.getText().isEmpty()) {
            show_user();
              clearfield();
            
        }

//          DefaultTableModel table =(DefaultTableModel)jTable_Display_User.getModel();
//        String search =searchID.getText().toLowerCase();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
//        jTable_Display_User.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchIDKeyReleased

    private void FEESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FEESKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }


    }//GEN-LAST:event_FEESKeyTyped

    private void FEESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEESActionPerformed
public void autoload(){
        String loadFees = (String) COURSELABEL.getSelectedItem();
        String querry = "SELECT * FROM course WHERE label=?";
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            conn = connectionDB.connection_DB();
            pst = conn.prepareStatement(querry);
            pst.setString(1, loadFees);
            rs = pst.executeQuery();
            if (rs.next()) {
                String setFEES = rs.getString("fees");
                FEES.setText(setFEES);
                String setSchedule = rs.getString("schedule");
                SCHEDULE.setText(setSchedule);

            }

        } catch (Exception e) {
        }



}
    private void COURSELABELPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_COURSELABELPopupMenuWillBecomeInvisible
        String loadFees = (String) COURSELABEL.getSelectedItem();
        String querry = "SELECT * FROM course WHERE label=?";
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            conn = connectionDB.connection_DB();
            pst = conn.prepareStatement(querry);
            pst.setString(1, loadFees);
            rs = pst.executeQuery();
            if (rs.next()) {
                String setFEES = rs.getString("fees");
                FEES.setText(setFEES);
                String setSchedule = rs.getString("schedule");
//                SCHEDULE.setText(setSchedule);

            }
            if (COURSELABEL.getSelectedIndex()==0) {
                FEES.setText("");
        
        
       
//        SCHEDULE.setText("");
        
        BATCHNAME.setSelectedIndex(0);
        FEES.setText("");
//        SCHEDULE.setText("");
                
            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_COURSELABELPopupMenuWillBecomeInvisible

    private void BATCHNAMEPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_BATCHNAMEPopupMenuWillBecomeInvisible
               String genarateS = (String) BATCHNAME.getSelectedItem();
        String querry = "SELECT * FROM course WHERE batch_name=?";
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            conn = connectionDB.connection_DB();
            pst = conn.prepareStatement(querry);
            pst.setString(1, genarateS);
            rs = pst.executeQuery();
            if (rs.next()) {
               
                String setSchedule = rs.getString("schedule");
                SCHEDULE.setText(setSchedule);

            }
            if (COURSELABEL.getSelectedIndex()==0) {
                FEES.setText("");
        
        
       
//        SCHEDULE.setText("");
        
        BATCHNAME.setSelectedIndex(0);
        FEES.setText("");
//        SCHEDULE.setText("");
                
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_BATCHNAMEPopupMenuWillBecomeInvisible

    private void BATCHNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BATCHNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BATCHNAMEActionPerformed

    private void searchIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchIDKeyTyped
         clearfield();
    }//GEN-LAST:event_searchIDKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
           HomeWindow hw = new HomeWindow();
        this.dispose();
        hw.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStudent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStudent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStudent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStudent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new manageStudent3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BATCHNAME;
    private javax.swing.JButton BTN_addStU1;
    private javax.swing.JComboBox<String> COURSELABEL;
    public static javax.swing.JTextField FEES;
    private javax.swing.JRadioButton FEMALE;
    private javax.swing.ButtonGroup GENDER;
    private javax.swing.JRadioButton MALE;
    private javax.swing.JTextField SCHEDULE;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel btn_backHome;
    private javax.swing.JButton cmd_save1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable_Display_User;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField searchID;
    private javax.swing.JTextArea txtADDRESS;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtPHONE;
    private javax.swing.JTextField txtPOSTCODE;
    // End of variables declaration//GEN-END:variables
    public void loadComboLABEL(JComboBox combo) {

        Connection conn = null;
        ResultSet rs = null;
        CallableStatement cst = null;

        try {
            conn = connectionDB.connection_DB();

            cst = conn.prepareCall("{CALL listlabel()}");
            cst.execute();
            rs = cst.getResultSet();
            List labelList = new ArrayList();

            while (rs.next()) {
                labelList.add(rs.getString(1));

            }

            combo.setModel(new DefaultComboBoxModel(labelList.toArray()));
            combo.insertItemAt("--Select One--", 0);
            combo.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                conn.close();
                cst.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
            public void loadScheduleList(JComboBox combo) {

        Connection conn = null;
        ResultSet rs = null;
        CallableStatement cst = null;

        try {
            conn = connectionDB.connection_DB();

            cst = conn.prepareCall("{CALL listSCHEDULE()}");
            cst.execute();
            rs = cst.getResultSet();
            List sch_lList = new ArrayList();

            while (rs.next()) {
                sch_lList.add(rs.getString(1));

            }

            combo.setModel(new DefaultComboBoxModel(sch_lList.toArray()));
            combo.insertItemAt("--Choose One--", 0);
            combo.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                conn.close();
                cst.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
    
    
    

}
